### ISSUE TITLE
datasets

### ISSUE THREAD

**Issue by nfrxqmllb** [Alejandro-Galan/Few-shot_COVID-19_Inter-vs-Intra#1]
Can you explain how the datasets are set up? What files are downloaded for different data sets?

**Comment by Alejandro-Galan** [comment]
There is no filter. Whole datasets were used. Nevermind, as all 4 datasets are publicly available, I can provide a temporary .zip with the folder I used. I will add the link in the README as soon as possible.

**Comment by Alejandro-Galan** [comment]
Uploaded temporary [here](https://drive.google.com/file/d/1-RiMzX3qdvBAFwy8jSYjPLixNqiN9-to/view?usp=sharing)
